---
name: Build the project
on:
  push:

jobs:
  win-release:
    runs-on: windows-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Build Windows x64 release
        shell: bash
        run: |
          bunx electron-builder --windows
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            dist/dsk_tables-win-x64.*
